In [26]:
import numpy as np
import cvxopt

In [27]:
diff_net = np.array([[0, .1, -.2, -.1],[.1, 0, .3, -.1],[-.2, .3, 0, .2],[-.1, -.1, .2, 0]])
print(diff_net)
N = diff_net.shape[0]
print(N)

[[ 0.   0.1 -0.2 -0.1]
 [ 0.1  0.   0.3 -0.1]
 [-0.2  0.3  0.   0.2]
 [-0.1 -0.1  0.2  0. ]]
4


In [28]:
P = np.triu(-diff_net)
print(P)

[[-0.  -0.1  0.2  0.1]
 [ 0.  -0.  -0.3  0.1]
 [ 0.   0.  -0.  -0.2]
 [ 0.   0.   0.  -0. ]]


In [29]:
q = np.sum(-diff_net, axis=0)
print(q)

[ 0.2 -0.3 -0.3  0. ]


In [30]:
G = np.zeros((2*N, N))
for i in range(N):
    G[2*i,i] = 1
    G[2*i+1,i] = -1
print(G)

[[ 1.  0.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0. -1.]]


In [31]:
h = np.ones(2*N)
print(h)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [33]:
P = cvxopt.matrix(P)
q = cvxopt.matrix(q)
G = cvxopt.matrix(G)
h = cvxopt.matrix(h)
sol = cvxopt.solvers.qp(P,q,G,h)

     pcost       dcost       gap    pres   dres
 0: -1.1000e-01 -9.2000e+00  9e+00  5e-17  3e-16
 1: -2.7313e-01 -1.1145e+00  8e-01  3e-16  4e-16
 2: -7.8687e-01 -8.4627e-01  6e-02  2e-16  2e-16
 3: -7.9987e-01 -8.0047e-01  6e-04  4e-16  8e-17
 4: -8.0000e-01 -8.0000e-01  6e-06  2e-16  1e-16
 5: -8.0000e-01 -8.0000e-01  6e-08  2e-16  8e-17
Optimal solution found.


In [38]:
print(sol['x'])
print(sol['primal objective'])

[-1.00e+00]
[ 1.00e+00]
[ 1.00e+00]
[ 0.00e+00]

-0.799999986504637
